[workspace]
default-members = ["bench", "pulldown-cmark", "pulldown-cmark-escape"]
members = [
  "bench",
  "dos-fuzzer",
  "fuzz",
  "pulldown-cmark",
  "pulldown-cmark-escape",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
