[build]
target = "x86_64-unknown-linux-gnu"
#rustc-wrapper = "sccache"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[target.x86_64-unknown-linux-gnu]
linker = "gcc"
rustflags = [
"-C", "strip=symbols",
"-C", "no-redzone=y",
"-C", "overflow-checks=y",
"-C", "lto=fat",
"-C", "embed-bitcode=y",
"-C", "codegen-units=1",
"-C", "opt-level=3",
"-C", "control-flow-guard=y",
"-C", "link-args=-Bmold -Wp,-D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIC -fpic -fPIE -fpie -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections",
]

[target.x86_64-unknown-linux-musl]
linker = "gcc"
rustflags = [
"-Clink-self-contained=on",
"-C", "strip=symbols",
"-C", "no-redzone=y",
"-C", "overflow-checks=y",
"-C", "lto=fat",
"-C", "embed-bitcode=y",
"-C", "codegen-units=1",
"-C", "opt-level=z",
"-C", "control-flow-guard=y",
"-C", "link-args=-Bmold -Wp,-D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIC -fpic -fPIE -fpie -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections",
]
[target.aarch64-unknown-linux-gnu]
linker = "gcc"
rustflags = [
"-C", "strip=symbols",
"-C", "no-redzone=y",
"-C", "overflow-checks=y",
"-C", "lto=fat",
"-C", "embed-bitcode=y",
"-C", "codegen-units=1",
"-C", "opt-level=3",
"-C", "control-flow-guard=y",
"-C", "link-args=-Bmold -Wp,-D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIC -fpic -fPIE -fpie -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections",
]

[target.aarch64-unknown-linux-musl]
linker = "gcc"
rustflags = [
"-Clink-self-contained=on",
"-C", "strip=symbols",
"-C", "no-redzone=y",
"-C", "overflow-checks=y",
"-C", "lto=fat",
"-C", "embed-bitcode=y",
"-C", "codegen-units=1",
"-C", "opt-level=3",
"-C", "control-flow-guard=y",
"-C", "link-args=-Bmold -Wp,-D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIC -fpic -fPIE -fpie -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections",
]

[target.x86_64-pc-windows-gnu]
#linker = "clang"
rustflags = [
"-C", "strip=symbols",
"-C", "no-redzone=y",
"-C", "overflow-checks=y",
"-C", "lto=fat",
"-C", "embed-bitcode=y",
"-C", "codegen-units=1",
"-C", "opt-level=3",
"-C", "control-flow-guard=y",
"-C", "link-args=-Wp,-D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIC -fpic -fPIE -fpie -Wl,--sort-common -Wl,--as-needed",
]

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin22.4-clang"
ar = "x86_64-apple-darwin22.4-ar"
rustflags = [
"-C", "strip=none",
"-C", "no-redzone=y",
"-C", "overflow-checks=y",
"-C", "lto=fat",
"-C", "embed-bitcode=y",
"-C", "codegen-units=1",
"-C", "opt-level=3",
"-C", "control-flow-guard=y",
"-C", "link-args=-Wp,-D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIC -fpic -fPIE -fpie",
]

[target.aarch64-apple-darwin]
linker = "aarch64-apple-darwin22.4-clang"
ar = "aarch64-apple-darwin22.4-ar"
rustflags = [
"-C", "strip=none",
"-C", "no-redzone=y",
"-C", "overflow-checks=y",
"-C", "lto=fat",
"-C", "embed-bitcode=y",
"-C", "codegen-units=1",
"-C", "opt-level=3",
"-C", "control-flow-guard=y",
"-C", "link-args=-Wp,-D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIC -fpic -fPIE -fpie",
]
