[build]
target = "x86_64-unknown-linux-musl"
rustc-wrapper = "sccache"

[unstable]
build-std = ["core", "compiler_builtins", "alloc", "std", "panic_abort"]
build-std-features = ["llvm-libunwind"]

[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = [
"-Clink-self-contained=on",
"-C", "strip=symbols",
"-C", "no-redzone=y",
"-C", "overflow-checks=y",
"-C", "lto=fat",
"-C", "embed-bitcode=y",
"-C", "codegen-units=1",
"-C", "opt-level=z",
"-C", "control-flow-guard=y",
"-C", "link-args=-fuse-ld=mold -Wp,-D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIE -fpie -Wl,-z,relro,-z,now",
]

[target.x86_64-pc-windows-gnu]
linker = "clang"
rustflags = [
"-C", "strip=symbols",
"-C", "no-redzone=y",
"-C", "overflow-checks=y",
"-C", "lto=fat",
"-C", "embed-bitcode=y",
"-C", "codegen-units=1",
"-C", "opt-level=z",
"-C", "control-flow-guard=y",
"-C", "link-args=-fuse-ld=mold -Wp,-D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIE -fpie -Wl,-z,relro,-z,now",
]

[target.x86_64-apple-darwin]
linker = "clang"
rustflags = [
"-C", "strip=symbols",
"-C", "no-redzone=y",
"-C", "overflow-checks=y",
"-C", "lto=fat",
"-C", "embed-bitcode=y",
"-C", "codegen-units=1",
"-C", "opt-level=z",
"-C", "control-flow-guard=y",
"-C", "link-args=-fuse-ld=mold -Wp,-D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIE -fpie -Wl,-z,relro,-z,now",
]

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = [
"-C", "strip=symbols",
"-C", "no-redzone=y",
"-C", "overflow-checks=y",
"-C", "lto=fat",
"-C", "embed-bitcode=y",
"-C", "codegen-units=1",
"-C", "opt-level=z",
"-C", "control-flow-guard=y",
"-C", "link-args=-fuse-ld=mold -Wp,-D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fPIE -fpie -Wl,-z,relro,-z,now",
]
