[build]
default-target = "x86_64-unknown-linux-gnu"    # use this target if none is explicitly provided
xargo = false                                    # enable the use of xargo by default
zig = true                                     # do not use zig cc for the builds
std = false
