name: Rust

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      working-directory: pulldown-cmark
      run: rustup default 1.74.0
    - name: Cargo build
      working-directory: pulldown-cmark
      run: cargo build --verbose --all
    - name: Cargo test
      working-directory: pulldown-cmark
      run: cargo test --verbose --all
    - name: Cargo test with simd feature enabled
      working-directory: pulldown-cmark
      run: cargo test --all --features=simd,gen-tests
    - name: Cargo test with serde feature enabled
      working-directory: pulldown-cmark
      run: cargo test --all --features=serde
    - name: Cargo test without default features
      working-directory: pulldown-cmark
      run: cargo test --all --no-default-features
    - name: Test for superlinear time regressions
      working-directory: fuzzer
      run: cargo run --release -- --regressions
